"""Email delivery service using SendGrid."""

from __future__ import annotations

import base64
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, select_autoescape

from config import firebase as firebase_config
from repositories import combined_document_repository


class EmailService:
    def __init__(self):
        template_root = Path(__file__).resolve().parents[1] / "templates"
        self._jinja = Environment(
            loader=FileSystemLoader(str(template_root)),
            autoescape=select_autoescape(["html"]),
        )

    def _sanitize_filename(self, value: str) -> str:
        return "".join(ch if ch.isalnum() or ch in {"_", "-", "."} else "_" for ch in value)

    def _build_subject(self, form_data: dict) -> str:
        merchant = form_data.get("merchant") or "Unknown Merchant"
        date = form_data.get("date") or form_data.get("dateOfHospitality") or "-"
        lang = form_data.get("language", "en")
        if lang == "de":
            return f"Ihr Folio Spesenbericht — {merchant} {date}"
        return f"Your Folio Expense Report — {merchant} {date}"

    def _build_plain_text(self, user_name: str, form_data: dict, pdf_download_url: str) -> str:
        merchant = form_data.get("merchant") or "-"
        date = form_data.get("date") or form_data.get("dateOfHospitality") or "-"
        category = form_data.get("expenseCategory") or "-"
        total = form_data.get("totalAmount") or 0
        return (
            f"Hello {user_name},\n\n"
            "Your Folio expense report is ready.\n"
            f"Merchant: {merchant}\n"
            f"Date: {date}\n"
            f"Category: {category}\n"
            f"Total Amount: EUR {float(total):.2f}\n\n"
            f"Download PDF: {pdf_download_url}\n\n"
            "This expense report was automatically generated by Folio.\n"
            "Support: support@folio.app\n"
        )

    def _build_html(self, user_name: str, form_data: dict, pdf_download_url: str) -> str:
        template = self._jinja.get_template("emails/pdf_delivery.html")
        return template.render(
            user_name=user_name,
            merchant=form_data.get("merchant") or "-",
            date=form_data.get("date") or form_data.get("dateOfHospitality") or "-",
            category=form_data.get("expenseCategory") or "-",
            total_amount=f"EUR {float(form_data.get('totalAmount') or 0):.2f}",
            pdf_download_url=pdf_download_url,
            support_email="support@folio.app",
        )

    def _send_via_sendgrid(
        self,
        to_email: str,
        subject: str,
        plain_text: str,
        html_content: str,
        pdf_bytes: bytes,
        filename: str,
    ) -> tuple[str | None, str | None]:
        from sendgrid import SendGridAPIClient
        from sendgrid.helpers.mail import (
            Attachment,
            Disposition,
            FileContent,
            FileName,
            FileType,
            Mail,
        )

        api_key = os.getenv("SENDGRID_API_KEY", "")
        from_email = os.getenv("SENDGRID_FROM_EMAIL", "noreply@folio.app")
        if not api_key:
            raise RuntimeError("SENDGRID_API_KEY is missing")

        message = Mail(
            from_email=from_email,
            to_emails=to_email,
            subject=subject,
            plain_text_content=plain_text,
            html_content=html_content,
        )
        encoded_pdf = base64.b64encode(pdf_bytes).decode("utf-8")
        message.attachment = Attachment(
            FileContent(encoded_pdf),
            FileName(filename),
            FileType("application/pdf"),
            Disposition("attachment"),
        )
        response = SendGridAPIClient(api_key).send(message)
        message_id = response.headers.get("X-Message-Id")
        if response.status_code >= 400:
            return None, f"SendGrid error: {response.status_code}"
        return message_id, None

    def send_pdf_delivery(
        self,
        to_email: str,
        user_name: str,
        form_data: dict,
        pdf_download_url: str,
        pdf_bytes: bytes,
        document_id: str,
    ) -> dict[str, Any]:
        subject = self._build_subject(form_data)
        plain_text = self._build_plain_text(user_name, form_data, pdf_download_url)
        html_content = self._build_html(user_name, form_data, pdf_download_url)
        filename = self._sanitize_filename(
            f"Folio_Expense_{form_data.get('merchant', 'merchant')}_{form_data.get('date') or form_data.get('dateOfHospitality') or 'date'}.pdf"
        )

        firebase_config.db.collection("combined_documents").document(document_id).set(
            {"emailDeliveryStatus": "pending"},
            merge=True,
        )
        try:
            message_id, error = self._send_via_sendgrid(
                to_email=to_email,
                subject=subject,
                plain_text=plain_text,
                html_content=html_content,
                pdf_bytes=pdf_bytes,
                filename=filename,
            )
            if error:
                firebase_config.db.collection("combined_documents").document(document_id).set(
                    {
                        "emailSent": True,
                        "emailSentAt": datetime.now(timezone.utc).isoformat(),
                        "emailMessageId": None,
                        "emailDeliveryStatus": "failed",
                    },
                    merge=True,
                )
                return {"success": False, "message_id": None, "error": error}

            combined_document_repository.update_email_status(document_id, "sent", message_id)
            return {"success": True, "message_id": message_id, "error": None}
        except Exception as exc:
            firebase_config.db.collection("combined_documents").document(document_id).set(
                {
                    "emailSent": True,
                    "emailSentAt": datetime.now(timezone.utc).isoformat(),
                    "emailMessageId": None,
                    "emailDeliveryStatus": "failed",
                },
                merge=True,
            )
            return {"success": False, "message_id": None, "error": str(exc)}


email_service = EmailService()


def send_pdf_delivery(
    to_email: str,
    user_name: str,
    form_data: dict,
    pdf_download_url: str,
    pdf_bytes: bytes,
    document_id: str,
) -> dict[str, Any]:
    return email_service.send_pdf_delivery(
        to_email=to_email,
        user_name=user_name,
        form_data=form_data,
        pdf_download_url=pdf_download_url,
        pdf_bytes=pdf_bytes,
        document_id=document_id,
    )
