"""Email delivery service using Resend."""

from __future__ import annotations

import base64
import json
import os
from urllib import error, request as urllib_request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, select_autoescape

from config import firebase as firebase_config
from repositories import combined_document_repository


class EmailService:
    def __init__(self):
        template_root = Path(__file__).resolve().parents[1] / "templates"
        self._jinja = Environment(
            loader=FileSystemLoader(str(template_root)),
            autoescape=select_autoescape(["html"]),
        )

    def _sanitize_filename(self, value: str) -> str:
        return "".join(ch if ch.isalnum() or ch in {"_", "-", "."} else "_" for ch in value)

    def _build_subject(self, form_data: dict) -> str:
        merchant = form_data.get("merchant") or "Unknown Merchant"
        date = form_data.get("date") or form_data.get("dateOfHospitality") or "-"
        lang = form_data.get("language", "en")
        if lang == "de":
            return f"Ihr Folio Spesenbericht — {merchant} {date}"
        return f"Your Folio Expense Report — {merchant} {date}"

    def _build_plain_text(self, user_name: str, form_data: dict, pdf_download_url: str) -> str:
        merchant = form_data.get("merchant") or "-"
        date = form_data.get("date") or form_data.get("dateOfHospitality") or "-"
        category = form_data.get("expenseCategory") or "-"
        total = form_data.get("totalAmount") or 0
        return (
            f"Hello {user_name},\n\n"
            "Your Folio expense report is ready.\n"
            f"Merchant: {merchant}\n"
            f"Date: {date}\n"
            f"Category: {category}\n"
            f"Total Amount: EUR {float(total):.2f}\n\n"
            f"Download PDF: {pdf_download_url}\n\n"
            "This expense report was automatically generated by Folio.\n"
            "Support: support@folio.app\n"
        )

    def _build_html(self, user_name: str, form_data: dict, pdf_download_url: str) -> str:
        template = self._jinja.get_template("emails/pdf_delivery.html")
        return template.render(
            user_name=user_name,
            merchant=form_data.get("merchant") or "-",
            date=form_data.get("date") or form_data.get("dateOfHospitality") or "-",
            category=form_data.get("expenseCategory") or "-",
            total_amount=f"EUR {float(form_data.get('totalAmount') or 0):.2f}",
            pdf_download_url=pdf_download_url,
            support_email="support@folio.app",
        )

    def _send_via_resend(
        self,
        to_email: str,
        subject: str,
        plain_text: str,
        html_content: str,
        pdf_bytes: bytes,
        filename: str,
    ) -> tuple[str | None, str | None]:
        api_key = os.getenv("RESEND_API_KEY", "")
        from_email = os.getenv("RESEND_FROM_EMAIL", "Folio <onboarding@resend.dev>")
        if not api_key:
            raise RuntimeError("RESEND_API_KEY is missing")

        payload = {
            "from": from_email,
            "to": [to_email],
            "subject": subject,
            "text": plain_text,
            "html": html_content,
            "attachments": [
                {
                    "filename": filename,
                    "content": base64.b64encode(pdf_bytes).decode("utf-8"),
                }
            ],
        }
        req = urllib_request.Request(
            "https://api.resend.com/emails",
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with urllib_request.urlopen(req, timeout=20) as response:
                body = response.read().decode("utf-8")
                decoded = json.loads(body or "{}")
                message_id = decoded.get("id")
                return message_id, None
        except error.HTTPError as exc:
            body = exc.read().decode("utf-8", errors="ignore")
            return None, f"Resend error: {exc.code} {body}"
        except Exception as exc:
            return None, str(exc)

    def send_pdf_delivery(
        self,
        to_email: str,
        user_name: str,
        form_data: dict,
        pdf_download_url: str,
        pdf_bytes: bytes,
        document_id: str,
    ) -> dict[str, Any]:
        subject = self._build_subject(form_data)
        plain_text = self._build_plain_text(user_name, form_data, pdf_download_url)
        html_content = self._build_html(user_name, form_data, pdf_download_url)
        filename = self._sanitize_filename(
            f"Folio_Expense_{form_data.get('merchant', 'merchant')}_{form_data.get('date') or form_data.get('dateOfHospitality') or 'date'}.pdf"
        )

        firebase_config.db.collection("combined_documents").document(document_id).set(
            {"emailDeliveryStatus": "pending"},
            merge=True,
        )
        try:
            message_id, error = self._send_via_resend(
                to_email=to_email,
                subject=subject,
                plain_text=plain_text,
                html_content=html_content,
                pdf_bytes=pdf_bytes,
                filename=filename,
            )
            if error:
                firebase_config.db.collection("combined_documents").document(document_id).set(
                    {
                        "emailSent": True,
                        "emailSentAt": datetime.now(timezone.utc).isoformat(),
                        "emailMessageId": None,
                        "emailDeliveryStatus": "failed",
                    },
                    merge=True,
                )
                return {"success": False, "message_id": None, "error": error}

            combined_document_repository.update_email_status(document_id, "sent", message_id)
            return {"success": True, "message_id": message_id, "error": None}
        except Exception as exc:
            firebase_config.db.collection("combined_documents").document(document_id).set(
                {
                    "emailSent": True,
                    "emailSentAt": datetime.now(timezone.utc).isoformat(),
                    "emailMessageId": None,
                    "emailDeliveryStatus": "failed",
                },
                merge=True,
            )
            return {"success": False, "message_id": None, "error": str(exc)}

    def send_email_with_html(
        self,
        api_key: str,
        from_email: str,
        to_email: str,
        subject: str,
        plain_text: str,
        html_content: str,
    ) -> dict[str, Any]:
        if not api_key or not from_email:
            return {"success": False, "message_id": None, "error": "Missing Resend configuration."}
        payload = {
            "from": from_email,
            "to": [to_email],
            "subject": subject,
            "text": plain_text,
            "html": html_content,
        }
        req = urllib_request.Request(
            "https://api.resend.com/emails",
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with urllib_request.urlopen(req, timeout=20) as response:
                body = response.read().decode("utf-8")
                decoded = json.loads(body or "{}")
                return {"success": True, "message_id": decoded.get("id"), "error": None}
        except error.HTTPError as exc:
            body = exc.read().decode("utf-8", errors="ignore")
            return {"success": False, "message_id": None, "error": f"Resend error: {exc.code} {body}"}
        except Exception as exc:
            return {"success": False, "message_id": None, "error": str(exc)}


email_service = EmailService()


def send_pdf_delivery(
    to_email: str,
    user_name: str,
    form_data: dict,
    pdf_download_url: str,
    pdf_bytes: bytes,
    document_id: str,
) -> dict[str, Any]:
    return email_service.send_pdf_delivery(
        to_email=to_email,
        user_name=user_name,
        form_data=form_data,
        pdf_download_url=pdf_download_url,
        pdf_bytes=pdf_bytes,
        document_id=document_id,
    )


def send_email_with_html(
    api_key: str,
    from_email: str,
    to_email: str,
    subject: str,
    plain_text: str,
    html_content: str,
) -> dict[str, Any]:
    return email_service.send_email_with_html(
        api_key=api_key,
        from_email=from_email,
        to_email=to_email,
        subject=subject,
        plain_text=plain_text,
        html_content=html_content,
    )
